import ProjectDescription

let workspace = Workspace(
    name: "Lemur",
    projects: ["Main", "LemmySwift", "Common", "Community", "Post", "Setting"],
    generationOptions: Workspace.GenerationOptions.options(autogeneratedWorkspaceSchemes: .disabled)
)

